name: Check

on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run unit-test
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run integration-test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build
