name: check

on: push

jobs:
  check:
    strategy:
      matrix:
        action: ['unit-test', 'integration-test', 'lint', 'build']
    runs-on: ubuntu-latest
    name: ${{matrix.action}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run ${{matrix.action}}
