name: pr environment

on: pull_request

jobs:
  pr-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://npm.pkg.github.com/
        scope: bradenhs
    - run: pwd
    - run: ls
    - run: npm publish --tag ${{github.sha}}
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
