name: pr environment

on: pull_request

jobs:
  pr-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry: https://npm.pkg.github.com
    - run: ls
    - run: npm config ls
    - run: npm publish --tag ${{github.sha}}
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
